name: Deploy Docs to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'api/docs/swagger.json'

jobs:
  trigger-vercel-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
