name: Deploy Docs to Vercel

on:
  push:
    branches:
      - master
    paths:
      - 'api/docs/swagger.json'

jobs:
  trigger-vercel-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment
        run: |
          if [ -z "$VERCEL_DEPLOY_HOOK_URL" ]; then
            echo "VERCEL_DEPLOY_HOOK_URL is not defined, skipping Vercel deploy."
            exit 0
          fi
          curl -X POST "$VERCEL_DEPLOY_HOOK_URL"
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
